/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ecf64a49-ed35-451e-943e-69d91cef60ed",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FeAhnNRHK",
    "aws_user_pools_web_client_id": "1f99tf0e8r0cbg4jh66l72hhqa",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://fimm4fuwxrbxri7ovv2arftuh4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "datingapitest4",
            "endpoint": "https://xzvevktiqg.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "initializeuserarrayt4",
            "endpoint": "https://0tyc1bj7z4.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "storeresultt4",
            "endpoint": "https://dpmmdbiq45.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "comsresultt4",
            "endpoint": "https://c2109vucp4.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "issresultt4",
            "endpoint": "https://u84fuih4rh.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        },
        {
            "name": "onetimestoret4",
            "endpoint": "https://hyoisymc0l.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ussenaterepcandsmain",
            "region": "us-west-2"
        },
        {
            "tableName": "ussenaterepcandsissues",
            "region": "us-west-2"
        },
        {
            "tableName": "ussenaterepcandscoms",
            "region": "us-west-2"
        },
        {
            "tableName": "usercandarraydisplay-staging",
            "region": "us-west-2"
        },
        {
            "tableName": "datinguserdb-staging",
            "region": "us-west-2"
        },
        {
            "tableName": "usstaterepcandsmain",
            "region": "us-west-2"
        },
        {
            "tableName": "usstaterepcandsissues",
            "region": "us-west-2"
        },
        {
            "tableName": "ushouserepcandsmain",
            "region": "us-west-2"
        },
        {
            "tableName": "ushouserepcandsissues",
            "region": "us-west-2"
        },
        {
            "tableName": "ushouserepcandscoms",
            "region": "us-west-2"
        },
        {
            "tableName": "midtermplaceholder-staging",
            "region": "us-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "test4images171405-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
